Feature/Lions-128 - Exibir preço "POR" do quilo em pesáveis
ObaHortifrutiDeveloper/oba.product-price pull request #1
Opened 2023-08-14 23:02 UTC by GustavoRosano

## Qual o propósito desse pull request ?

<em>PR aberto para adicionar a informa~ção de Preço "POR" do kg em produtos pesáveis sem desconto.</em>

## Tipo de mudança

<em>Delete as opções que não se encaixem</em>

- [ ] Bug fix (Uma mudança que corrige um problema)
- [x] New feature (Mudança que adiciona funcionalidade)
- [ ] Breaking change (Correção ou recurso que faria com que a funcionalidade existente não funcionasse como esperado)
- [ ] Esta alteração requer uma atualização da documentação

## Como a mudança funciona ?

<em>A mudança faz com que os produtos pesáveis sem desconto tenham o preço por Kg aparente junto com o preço final para melhor entendimento dos usuários. Além de também corrigir a padronização da informação KG.</em>

## Como isso pode ser testado ?

> Descrição:
<em>Procure na loja produtos pesáveis sem desconto.</em>

> Workspace:
<em>[Lions-128](https://lions128--obahortifruti.myvtex.com/)</em>

## Qual task esse pull request soluciona ?

<em>[Lions-128 - Exibir preço "POR" do quilo em pesáveis](https://redeoba.atlassian.net/browse/LIONS-128)</em>
<em>[Lions-127 - Correção/ padronização de info "/ kg"](https://redeoba.atlassian.net/browse/LIONS-127)</em>

## Referências

<em>https://developers.vtex.com/docs/guides/vtex-io-documentation-using-css-handles-for-store-customization#best-practices</em>

## Checklist

**PR Titulo e Mensagens de Commit**

- [x] O título do PR e as mensagens de commit seguem o [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
  - Prefixos Disponíveis: `feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, and `test`

**PR Descrição**

- [x] Adicionar a label do PR de acordo com o contexto do mesmo - `Bug`, `Documentation`, `Done`, `Duplicate`, `Feature`, `Help Wanted`, `Invalid`, `Question`, `Request Changes`, `With Conflict`, `WontFix`, e `Work In Progress`

**Documentação**

- [x] PR description

**Código**

- [x] Meu código segue os padrões de estilo do projeto
- [x] Eu fiz uma autoavaliação do meu próprio código
- [ ] Eu comentei meu código, especialmente em áreas difíceis de entender
- [x] Minhas alterações não geram novos warnings

2023-08-15 20:51 UTC, kaisukidev commented
@GustavoRosano Branch errada, o PR está enviando para a master antes da develop.

2023-08-15 20:53 UTC, kaisukidev requested changes
Existem algumas alterações a serem feitas

2023-08-15 20:53 UTC, kaisukidev commented on manifest.json
>    "version": "1.31.0",
Troca a versão para 0.0.1 por favor.

2023-08-15 20:53 UTC, kaisukidev commented on react/SellingPrice.tsx
> +  // const shouldRenderSellingPriceValue = hasKg && hasListPrice
Remover o trecho comentado.

2023-08-15 21:15 UTC, mdanilo approved these changes

2023-08-15 21:23 UTC, GustavoRosano commented on manifest.json
>    "version": "1.31.0",
Feito

2023-08-15 21:23 UTC, GustavoRosano commented on react/SellingPrice.tsx
> +  // const shouldRenderSellingPriceValue = hasKg && hasListPrice
Feito

2023-08-17 12:17 UTC, kaisukidev approved these changes

2023-08-17 12:17 UTC, merged